[package]
name = "rss-webhook-trigger"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
rust-version = "1.57.0"

[dependencies]
rss = "2.0.6"
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls", "json"] }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread", "signal"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
toml = "0.8.8"
color-eyre = "0.6.2"
env_logger = "0.10.1"
log = "0.4.20"
time = { version = "0.3.31", features = ["serde", "serde-well-known"] }
