[package]
name = "rss-webhook-trigger"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
rust-version = "1.67.0"
license = "MIT"

[dependencies]
rss = "2.0.7"
reqwest = { version = "0.12.2", default-features = false, features = ["rustls-tls", "json"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "signal"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
toml = "0.8.8"
color-eyre = "0.6.3"
env_logger = "0.10.2"
log = "0.4.21"
time = { version = "0.3.34", features = ["serde", "serde-well-known"] }
secretfile = "0.1.0"
