[package]
name = "rss-webhook-trigger"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
rss = "2.0.1"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls", "json"] }
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread", "signal"] }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
toml = "0.5.9"
color-eyre = "0.6.2"
env_logger = "0.9.0"
log = "0.4.17"
time = { version = "0.3.11", features = ["serde", "serde-well-known"] }
